### ISSUE TITLE
Tracking Drives - timezone for days is UTC

### ISSUE THREAD

**Issue by ceboxsell** [jheredianet/Teslamate-CustomGrafanaDashboards#107]
In the Tracking Drives report you select the date and it lists the drives to pick from.
For me I am in UTC + 10 or 11 hours this means a drive starting at 7 am appears in the list for the day before but the actual details have the correct date.
Example below. The drop down list was the 28th, the drive was the 29th. If I go to the next day I can see drives starting after 11AM on that day
Not a big issue at all but thought you might like to know.

<img width="688" alt="image" src="https://github.com/user-attachments/assets/d716d58a-cb47-4f50-833b-ff3d981e7362" />

**Comment by swiffer** [comment]
@ceboxsell thanks raising the issue. A fix is a beeing added as part of #108

**Comment by ceboxsell** [comment]
Sorry this fix is not correct.
The drive now appears in the drop down list as the correct day  but it is changed from the actual day.
Select the drive, get data and you see the actual date.

<img width="704" alt="Image" src="https://github.com/user-attachments/assets/8e63a266-3de9-49ac-bba3-de6abeba8470" />

**Comment by ceboxsell** [comment]
I should clarify, the drive appears as the same date as the drop down list but this is the date adjusted to UTC in the drop down. The drive should appear for the day. 
The drive should appear in the list under the 29th not the 28th.
Again not a big issue, won't end the world.

**Comment by swiffer** [comment]
I expected exactly this to happen. You are sure to be using the latest master? (Dashboard not modified locally?)

Could you post the variable query from the dashboard settings for day?

**Comment by ceboxsell** [comment]
I have not made any modifications and pulled the latest version before trying again.
The screen shot shows exactly what I did. When I select the  Nov 28 2024 it shows the drives for the day. It lists one using the date for that day but it was not on that day.

<img width="667" alt="Image" src="https://github.com/user-attachments/assets/32848ac5-eb17-4a34-85d8-71f720bc2e0f" />
As you can see the drive shows as 28-11-24 but in reality it started on the 29th as per the details box

<img width="640" alt="Image" src="https://github.com/user-attachments/assets/6e2b1b37-fc11-4513-a806-149572f6386e" />

The new code modified the menu name to UTC time instead of listing in local time.

**Comment by ceboxsell** [comment]
FYI I just restarted my containers to be sure.
(SELECT TO_CHAR(timezone('UTC', start_date), 'DD') as day FROM drives WHERE car_id = $car_id ORDER BY start_date DESC LIMIT 1)
UNION ALL
(SELECT TO_CHAR(timezone('UTC', start_date), 'DD') as day FROM drives 
WHERE  car_id = $car_id AND TO_CHAR(timezone('UTC', start_date), 'YYYY') = '$Year'  AND TO_CHAR(timezone('UTC', start_date), 'MM') = '$Month'
GROUP BY 1 ORDER BY 1);

Still the same error.  Sorry don't mean to confuse you.

**Comment by swiffer** [comment]
ok, second query / comment looks good.

what timezone is set in your grafana profile?

**Comment by ceboxsell** [comment]
AEDT 

<img width="470" alt="Image" src="https://github.com/user-attachments/assets/850d1f34-b5a9-41d7-ab95-d286d4a6d01b" />

**Comment by swiffer** [comment]
and the variable selector is now still showing 28th instead of 29th?

**Comment by ceboxsell** [comment]
Alas yes.  Still has the 28th in the drop down when the drive was the 29th 7AM which is 28th 8PM UTC

<img width="602" alt="Image" src="https://github.com/user-attachments/assets/bac1a172-06ed-4f10-a8f8-3a27d5698cd7" />

**Comment by swiffer** [comment]
That triggers me :-D it should have been corrected by the PR I opened. Will try to replicate this with some drives i gathered over time.

Is your grafana instance hosted via docker compose? have you set TZ / PGTZ env vars for the containers?

**Comment by ceboxsell** [comment]
It is hosted via compose. From the teslamate install instructions.
Teslamate has TZ set to my timezone. Grafana does not, will check on options there and if it helps let you know.

**Comment by ceboxsell** [comment]
added environment - TZ=${TM_TZ} and still the same issue. Again don't stress :)

**Comment by swiffer** [comment]
Hi @ceboxsell - checked this again with a drive in my instance (CEST / UTC).

Database (UTC)
![Image](https://github.com/user-attachments/assets/826d17dd-239e-43ad-8cdc-be283dbcb87f)

Dashboard (Europe/Berlin)
![Image](https://github.com/user-attachments/assets/e3c5a9fc-0550-4137-8b79-36e120dbfcbc)

That's how it should be, right?

**Comment by ceboxsell** [comment]
It does look correct there.
